name: Build package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
  upload-release:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: ${{github.workspace}}/dist
      - name: Display downloaded files
        run: ls ${{github.workspace}}/dist
      - name: Upload release
        run: |
            gh release upload ${{github.event.release.tag_name}} dist/*.whl dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
  test-pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - upload-release
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write

    environment:
      name: testpypi
      url: https://test.pypi.org/p/libertem-ui

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/
          verbose: true
