name: Build package

on:
  release:
    types: [prereleased]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
  upload-release:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      contents: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
      - name: Display structure of downloaded files
        run: ls -R          
      # - name: Upload release
      #   run: |
      #       cd ${{github.workspace}}
      #       gh release upload ${{github.event.release.tag_name}} feedmd-win-x64.zip
      #   env:
      #     GITHUB_TOKEN: ${{ github.TOKEN }}
